#!/usr/bin/env python3
"""Build kb/_index.md: one line per doc — path, title, first-paragraph summary.

Run after adding or editing KB docs. The index is generated; never hand-edit.
"""

import os
import sys
from pathlib import Path

KB_DIR = Path(os.environ.get("KB_DIR", Path(__file__).resolve().parent.parent / "kb"))
INDEX_FILE = KB_DIR / "_index.md"
SUMMARY_MAX_CHARS = 160


def summarize(doc: Path) -> tuple[str, str]:
    """Return (title, one-line summary) for a markdown doc."""
    title, summary_lines = doc.stem, []
    in_frontmatter = False
    for raw in doc.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if line == "---" and not summary_lines and title == doc.stem:
            in_frontmatter = not in_frontmatter
            continue
        if in_frontmatter or not line or line.startswith(("```", "|", "!", "<")):
            if summary_lines and not line:
                break  # end of first paragraph
            continue
        if line.startswith("#"):
            if title == doc.stem:
                title = line.lstrip("# ").strip()
            continue
        summary_lines.append(line)
    summary = " ".join(summary_lines)
    if len(summary) > SUMMARY_MAX_CHARS:
        summary = summary[: SUMMARY_MAX_CHARS - 1].rsplit(" ", 1)[0] + "…"
    return title, summary


def main() -> int:
    docs = sorted(p for p in KB_DIR.rglob("*.md") if p.name != "_index.md")
    if not docs:
        print(f"No .md files under {KB_DIR}", file=sys.stderr)
        return 1
    lines = ["# KB Index", "", "<!-- generated by scripts/build_index.py — do not edit -->", ""]
    for doc in docs:
        rel = doc.relative_to(KB_DIR)
        title, summary = summarize(doc)
        lines.append(f"- `{rel}` — **{title}**: {summary}")
    INDEX_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {INDEX_FILE} ({len(docs)} docs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
